### ISSUE TITLE
If no Workspace open, we should show option to user to start process of choosing folder to open

### ISSUE THREAD

**Issue by bishal-pdMSFT** [hiyadav/azure-pipelines-vscode#20]
1. Open VS Code with no workspace open
2. Start "configure pipeline" command
3. It will ask for login. Click on that it will take to browser
4. Authneticate there and come back
5. Automatically a "open folder" dialog is being shown. This is very confusing. we should first intimate user that no workspace is open and he has to open a folder.

**Comment by hiyadav** [comment]
@pulkitaggarwl to consider.

**Comment by hiyadav** [comment]
Text for dialog: Select source folder for configuring pipeline
