### ISSUE TITLE
Github: "Failed to configure Azure pipeline. Error: Repository ID for a GitHub repository should be in the form: OwnerName/Repository."

### ISSUE THREAD

**Issue by tejasd1990** [hiyadav/azure-pipelines-vscode#22]
Some string got attached to the repo url. The Url in the service endpoint was like "OwnerName/Repository/randomstring"

**Comment by hiyadav** [comment]
@tejasd1990 it would be really helpfull if you can provide the repo name that you were using. Will make the task easier for us to debug.

**Comment by tejasd1990** [comment]
https://github.com/tejasd1990/node_containers_from_dps. This is the repo I used.
