### ISSUE TITLE
[Suggestion] Configure Pipeline option in command palette should consider the selected folder

### ISSUE THREAD

**Issue by amaljg** [hiyadav/azure-pipelines-vscode#35]
Repro Steps:

1. Open the parent folder of any git repo.
2. Select the git repo folder in the explorer.
3. Open command palette and select _Azure Pipelines: Configure Pipeline_ option.
4. The command fails with error `Selected workspace is not a git repository...`. (snapshot below)

![Error2](https://user-images.githubusercontent.com/19945729/63638322-5d136880-c6a4-11e9-9fd5-da4873a5b206.png)

This is a bit confusing since the _Right click -> Configure Pipeline_ option works on the selected folder, but not the command palette command.

**Comment by hiyadav** [comment]
If more than one folder is opened in a workspace, then show a dropdown to select a folder. 
TEXT: 'Select a folder from current workspace to deploy'

**Comment by bishal-pdMSFT** [comment]
We need to update "Working directory" input in yaml
