### ISSUE TITLE
'Select Azure DevOps Project' option gets stuck forever sometimes

### ISSUE THREAD

**Issue by amaljg** [hiyadav/azure-pipelines-vscode#37]
'Select Azure DevOps Project' option gets stuck forever sometimes (snapshot below). The issue went away after restarting VSCode. Note that this has gone past the org selection - it was able to successfully list all orgs. So there are no issues with the VSCode instance. 

![Error4](https://user-images.githubusercontent.com/19945729/63638427-5d603380-c6a5-11e9-96bc-8933674312cd.png)

There are 2 issues here:
1. Why the _'Select Azure DevOps Project'_ option was not listing the projects?
2. Even if for some reason the projects could not be listed, the UX should have timed out and showed some failure message to the user.

**Comment by bishal-pdMSFT** [comment]
Closing as no repro
