### ISSUE TITLE
Configure Pipeline option does not handle the line endings correctly when checking-in the pipelines YAML

### ISSUE THREAD

**Issue by amaljg** [hiyadav/azure-pipelines-vscode#38]
Configure Pipeline option does not handle the line endings correctly when checking-in the pipelines YAML, resulting in the error `fatal: LF would be replaced by CRLF...` (snapshot below)'

![Error5](https://user-images.githubusercontent.com/19945729/63638463-d95a7b80-c6a5-11e9-9ac8-b5f5c7361e9d.png)

**Comment by amaljg** [comment]
Find below my git config:

> λ git config --list
core.symlinks=true
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
credential.helper=manager
user.name=*********************
user.email=*************
core.safecrlf=true
core.preloadindex=true
core.fscache=true
core.whitespace=cr-at-eol
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
push.default=simple
rerere.enabled=true
gui.fontdiff=-family "Fira Code Retina" -size 10 -weight normal -slant roman -underline 0 -overstrike 0
gui.tabsize=2
credential.helper=manager
alias.pr=!f() { exec vsts code pr "$@"; }; f
alias.repo=!f() { exec vsts code repo "$@"; }; f
diff.tool=meld
diff.guitool=meld
difftool.prompt=true
difftool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsdiffmerge.exe" "$LOCAL" "$REMOTE" //t
difftool.vsdiffmerge.keepbackup=false
difftool.meld.prompt=false
difftool.meld.cmd="C:/Program Files (x86)/Meld/meld.exe" "$LOCAL" "$REMOTE"
difftool.meld.path=C:/Program Files (x86)/Meld/meld.exe
merge.tool=meld
mergetool.prompt=true
mergetool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsdiffmerge.exe" "$REMOTE" "$LOCAL" "$BASE" "$MERGED" //m
mergetool.vsdiffmerge.keepbackup=false
mergetool.vsdiffmerge.trustexitcode=true
mergetool.meld.prompt=false
mergetool.meld.keepbackup=false
mergetool.meld.keeptemporaries=false
mergetool.meld.path=C:/Program Files (x86)/Meld/meld.exe
mergetool.meld.cmd="C:/Program Files (x86)/Meld/meld.exe" "$LOCAL" "$BASE" "$REMOTE" --output "$MERGED"
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=**************
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin2.url=***************
remote.origin2.fetch=+refs/heads/*:refs/remotes/origin2/*
remote.origin3.url=*************
remote.origin3.fetch=+refs/heads/*:refs/remotes/origin3/*
gui.wmstate=normal
gui.geometry=1109x563+128+128 216 255

**Comment by hiyadav** [comment]
For this error, give a helping error message along with the message:
1. Commit failed: git error message.
